### ISSUE TITLE
Hong Kong Address Format

### ISSUE THREAD

**Issue by jack-booxi** [fragaria/address-formatter#295]
Hi, team
The version I am using is src="https://unpkg.com/@fragaria/address-formatter@2.3.0"
The config example is 
var formatted = window.addressFormatter.format({
        "houseNumber": "",
        "road": "211 Test Street",
        "neighbourhood": "",
        "city": "Hong Kong",
        "postcode": "",
        "county": "",
        "state": "",
        "country": "Hong Kong",
        "countryCode": "HK",
    }, {
        output: 'array'
    });
The output result will just show "211 Test Street".
Is this an issue or is there any work around for this?
Thank you for your attention!

**Comment by JirkaChadima** [comment]
Hi, this is really just a Javascript implementation, we don't maintain the formatting rules. So I'd like to ask you to open the same issue against https://github.com/OpenCageData/address-formatting/ since that's the right place to discuss the wrong formats. I will later reflect that in a newer version of this library
