### ISSUE TITLE
Only drop node LTS version support in major releases 

### ISSUE THREAD

**Issue by Tapppi** [fragaria/address-formatter#562]
There are now multiple breaking changes within minor versions, in that you are dropping LTS version support in a minor version release. This breaks the library for users still on those LTS versions. For example, node 12 is still a supported LTS versions, yet this library has broken compatibility without a major release support. If you look at the major packages from npm, they all drop support for LTS versions in major releases, letting users acknowledge the dropped versions.

**Comment by JirkaChadima** [comment]
Hi @Tapppi , apologies about that. I didn't realize that it has implications in the user-land code. I am looking at the semver mostly from the perspective from the JS API of the library.

Since Node 12 goes [out of support in 21 days](https://nodejs.org/en/about/releases/), I don't think it's a big deal. You'll need to upgrade your codebase anyway
